name: noarman_professional_downloader
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+2

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  path_provider: ^2.0.0
  permission_handler: ^10.0.0
  intl: ^0.19.0
  file_picker: ^7.1.0+1
  shared_preferences: ^2.3.2
  open_file: ^3.5.3
  flutter_foreground_task: ^8.8.1+1
  dio: ^5.7.0
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true



flutter_native_splash:

  color: "#f8fbf2"
  image: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

  android_12:
    
    color: "#f8fbf2"
    branding: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
